model:
  backbone: resnet18
  ckpt_pretrained: weights/supcon_first_stage/swa
  num_classes: 44

train:
  n_epochs: 50
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  ema: True
  ema_decay: 0.99
  logging_name: supcon_second_stage
  target_metric: accuracy
  stage: second # first = Supcon, second = FC finetuning for classification

dataset: data/product_version3

dataloaders:
  train_batch_size: 200 # the higher - the better
  valid_batch_size: 200
  num_workers: 12 # set this to num of threads in your CPU

optimizer:
  name: SGD
  params:
    lr: 0.1

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 50
    eta_min: 0.01

criterion:
  name: 'LabelSmoothing'
  params:
    smoothing: 0.01
    classes: 44
