train:
  n_epochs: 100
  backbone: resnet18
  ckpt_pretrained:
  amp: True # set this to True, if your GPU supports FP16. 2080Ti - okay, 1080Ti - not okay
  logging_name: supcon_first_stage
  target_metric: precision_at_1
  stage: first # first = Supcon, second = FC finetuning for classification

dataset:
  data_dir: data/product_version3
  num_classes: 44

dataloaders:
  train_batch_size: 200 # the higher - the better
  valid_batch_size: 200
  num_workers: 12 # set this to num of threads in your CPU

optimizer:
  name: SGD
  params:
    lr: 0.1

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 100
    eta_min: 0.01

criterion:
  name: 'SupCon'
  params:
    temperature: 0.1

